[package]
name = "cloudy-rest"
version = "0.1.0"
edition = "2021"

[profile.dev]
incremental = true

[profile.release]
incremental = true
lto = true
opt-level = 3
overflow-checks = true
strip = true

[dependencies.rocket]
version = "0.5.1"
